version: "3.2"
services:

  docker_db:
    image: mysql:5.7.22
    volumes:
      - type: bind
        source: /home/volume/mysqldb
        target: /var/lib/mysql/
    networks:
      - gallery-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ThePassword
      - MYSQL_DATABASE=gallery
      - MYSQL_USER=spring
      - MYSQL_PASSWORD=ThePassword
    ports:
      - 23306:3306

  gallery:
    build: ./server
    restart: on-failure
    volumes:
      - type: bind
        source: /home/volume/resources
        target: /server/resources/
    ports:
      - "80:8080"
    networks:
      - gallery-mysql
    depends_on:
      - docker_db

networks:
  gallery-mysql:

