FROM java:8-jdk-alpine

WORKDIR /app

# copy the packaged jar file into our docker image
COPY target/server-1.0.jar /server.jar

EXPOSE 8080

# set the startup command to execute the jar
CMD ["java", "-jar", "/server.jar"]